### ISSUE TITLE
Can this program run on the remote server?

### ISSUE THREAD

**Issue by PaulWu-China** [LevonPython/PbiRefresher#1]
Hello!
Can this program run on the remote server? i know it needs the user logon, but can it work to run in windows scheduler after the disconnection of the user logon? Thanks a lot.

**Comment by LevonPython** [comment]
Hello!

User of pbix should be logged in order to be able to publish it.
Please keep in mind that this script uses GUI of Power BI Desktop and it needs that a user is logged in Windows session.

**Comment by LevonPython** [comment]
Hello!

User of pbix should be logged in order to be able to publish it.
Please keep in mind that this script uses GUI of Power BI Desktop and it needs that a user is logged in Windows session.
