### ISSUE TITLE
Can I Schedule this (through windows task scheduler) to run automatically on Remote Server?

### ISSUE THREAD

**Issue by pystory** [LevonPython/PbiRefresher#2]
Hello, 

Thank you so much for putting up this approach of refreshing Power BI files. I was able to use this script with minor modifications to refresh power BI files.

I then scheduled task on windows scheduler to run this at scheduled time. It did open the power BI instance but didn't do anything further and didn't even give any error. In the Task settings. I have kept 'Run only when user is logged on'. Is there a way I can make this work to use it through scheduled task?

I am not trying to publish to power bi service. I just want to open a file, refresh, save and close it. I would highly appreciate any help on this. I am using Python 3.7.6 and Power BI Desktop 2.90.782.0

Thanks,

**Comment by LevonPython** [comment]
Hello , 
Thank you for your feedback,
First of all you can just remove the portion of script you don't need (for example publish portion) and run the script for only open/refresh/save etc.
I think script way is  the best way to do your job. 
But it is also possible to make it via windows task.
For example you can find similar info in this [website](https://www.isunshare.com/windows-10/4-ways-to-open-task-scheduler-on-windows-10.html#:~:text=4%20ways%20to%20open%20Task%20Scheduler%20on%20Windows,2.%20%3A%20Click%20Task%20Scheduler%20on%20the%20left.) . and also this [one](http://blogs.inservit.com/schedule-to-refresh-power-bi-dataset-using-pbihelper/).
I hope this helps you.
Good luck!
