### ISSUE TITLE
This code does not appear to work anymore

### ISSUE THREAD

**Issue by oxbluegit** [LevonPython/PbiRefresher#3]
Cannot meet the requirements.txt due to the fact there is no matching distribution found for opencv-contrib-python==4.2.0.32

 No matching distribution found for opencv-python==4.2.0.32 on Python 3.10.10.

Is there any way to troubleshoot this

**Comment by LevonPython** [comment]
Hello, this can happen because the python version used for this script is 3.7 (as described in the REAME file).  Try out the same version of python 3.7 as in the description file with opencv-python==4.2.0.32 version.
